### ISSUE TITLE
PP value not matching

### ISSUE THREAD

**Issue by ohmaytt** [uyitroa/osr2mp4-app#10]
App's PP
![image](https://user-images.githubusercontent.com/45356936/87241195-8d4e2c00-c45b-11ea-917b-cc0406a8089e.png)

Actual PP
![image](https://user-images.githubusercontent.com/45356936/87241210-a951cd80-c45b-11ea-9366-dbf764008a12.png)

**Comment by McKay42** [comment]
This is using [oppai/ezpp](https://github.com/Francesco149/oppai-ng), which will be inaccurate by default because it doesn't calculate slider curves (among other smaller differences).
