### ISSUE TITLE
Sliders not showing up correctly when using high fps amounts and hidden together

### ISSUE THREAD

**Issue by obvRedwolf** [uyitroa/osr2mp4-app#104]
title

https://www.youtube.com/watch?v=dnHA4VQgK4g

it only does that for over 120 fps amounts

**Comment by uyitroa** [comment]
@redwolf185 sorry for the late reply,
you need to update your app. There is a button bottom left

**Comment by obvRedwolf** [comment]
havent seen this in 2 years
