### ISSUE TITLE
Support for other gamemodes (o!m/o!t/o!c)

### ISSUE THREAD

**Issue by tasnimtamim** [uyitroa/osr2mp4-app#13]
As of now, I think the support for other 3 modes such as mania, taiko and ctb is not present. When trying to generate mp4 for a osu!mania replay, the program shows this error: "KeyError('end time')'end time'
![image](https://user-images.githubusercontent.com/52713990/87247592-94cefe80-c476-11ea-9e77-3d00de54386d.png)

Here is the log: https://tamim.s-ul.eu/otmUlyDa

Thanks!

**Comment by jsumabat** [comment]
Currently, there is no support for the other 3 game modes. 😔

**Comment by uyitroa** [comment]
There won't be any support for 3 others game modes since implementing osu std is already hard enough.
