### ISSUE TITLE
How i add skins?

### ISSUE THREAD

**Issue by ghost** [uyitroa/osr2mp4-app#130]
I can't change the "default skin" option
![image](https://user-images.githubusercontent.com/72302817/152877083-d2f4e0fe-76d5-471e-a23d-ce78ea06e046.png)

**Comment by AruHonshou2000** [comment]
That also happened to me, I've just restarted Osr2mp4 and it fixed

**Comment by WhiteSnow00** [comment]
Open osr2mp4 config,and link it to your skin folder
