### ISSUE TITLE
The conversion does not start

### ISSUE THREAD

**Issue by XqMine0** [uyitroa/osr2mp4-app#140]
When I try to convert my replay the conversion doesn't start and stop at 0%.
![image](https://user-images.githubusercontent.com/107318497/184496979-79b317af-f575-4c8a-a7b7-7602b3a4d89d.png)

hope some1 can help

**Comment by uyitroa** [comment]
@XqMine0 use legacy version

**Comment by XqMine0** [comment]
> @XqMine0 use legacy version

it worked, thanks
