### ISSUE TITLE
'NoneType' object is not subscriptable

### ISSUE THREAD

**Issue by TheShadowEevee** [uyitroa/osr2mp4-app#19]
Using the latest release, v0.1, attempting to set the "osu!" folder when prompted on first boot immediately crashes the program. According to the traceback in the attached appoutput.log, I think the error is occurring when trying to log the location of the beatmap folder.
[appoutput.log](https://github.com/uyitroa/osr2mp4-app/files/4920264/appoutput.log)
I've tried running the program a few times but nothings changed. I made sure the osu! directory didn't have anything different then usual as well.

**Comment by uyitroa** [comment]
run reset.exe, then rerun the app. Click on the update button.

**Comment by TheShadowEevee** [comment]
That fixed it. Thanks!
