### ISSUE TITLE
Default to mp4 output

### ISSUE THREAD

**Issue by jxu** [uyitroa/osr2mp4-app#25]
currently defaults to avi

**Comment by Hoshiiiii** [comment]
change .avi to .mp4 in the output name(settings)

**Comment by MathisBicheyre** [comment]
> 
> 
> change .avi to .mp4 in the output name(settings)

I think he means you should switch to mp4 in default because it's a superior container

**Comment by cainy-a** [comment]
AFAIK mp4 doesn't support XVID, to do this most likely you would need ffmpeg exporter on by default AND to bundle ffmpeg with it, which could get problematic with licensing.

**Comment by redwolf185** [comment]
> AFAIK mp4 doesn't support XVID, to do this most likely you would need ffmpeg exporter on by default AND to bundle ffmpeg with it, which could get problematic with licensing.

mp4 works for me.

**Comment by jxu** [comment]
XVID is one codec for MPEG-4 Visual ASP. Anyhow it's GPL'd so if you use it then you shouldn't have any qualms with ffmpeg which is also GPL.
