### ISSUE TITLE
Really slow conversion

### ISSUE THREAD

**Issue by Desmond823** [uyitroa/osr2mp4-app#48]
I tried converting one of my replays and it takes a really long time. I've waited for 30 minutes and the replay hasn't been converted. How do I speed up the conversion?

**Comment by uzervlad** [comment]
You don't. Python sucks ass

**Comment by uyitroa** [comment]
@uzervlad Well it really depends on his settings and spec because osr2mp4 can render a 1080p@60fps play faster than recording on a normal pc.
By the way he also opened the same issue on the osr2mp4-core repo and I asked him about his settings and specs but he didn't answer for months.
