### ISSUE TITLE
Getting Error when trying to convert Replay

### ISSUE THREAD

**Issue by NekoMiku39** [uyitroa/osr2mp4-app#49]
Everytime I click on the start button I get this Error Message : TypeError("object of type 'NoneType' has no len()")object of type 'NoneType' has no len()
![Desktop Screenshot 2020 10 29 - 18 39 57 39](https://user-images.githubusercontent.com/52016243/97611317-4b4ef300-1a16-11eb-88dd-0a5be7dea689.png)

**Comment by uyitroa** [comment]
Does it work on others maps? Or others skins?
If so, can you send me the map and replay that have the error

**Comment by PlasticMatic** [comment]
Me and a friend have the same issue, is there any solution?

**Comment by uyitroa** [comment]
Does it work on others maps? Or others skins?
If so, can you send me the map and replay that have the error

**Comment by PlasticMatic** [comment]
Yeah it works in other maps and with the same skin, but only for std, I tried with a replay of mania and didn't work and my friend was trying to convert a taiko replay, I didn't read about that but does it just work for std replays? However, here's the replay and the map (I'm not an expert on mania so srry if the replay sucks a little)
[Nippon Egao Hyakkei Rp and map.zip](https://github.com/uyitroa/osr2mp4-app/files/5519692/Nippon.Egao.Hyakkei.Rp.and.map.zip)

**Comment by uyitroa** [comment]
Yeah unfortunately only std mode is supported.
