### ISSUE TITLE
What does "process" in the settings mean?

### ISSUE THREAD

**Issue by Vaarelsauce** [uyitroa/osr2mp4-app#50]
Is it referring to my CPU's threads or core count?

Also, can you add a feature to select pre-existing resolutions? Like an option for 3840x2160, 1920x1080, 1280x720, 480x360, 180p etc. . . or like a % downscale of the current recorded resolution?

**Comment by uyitroa** [comment]
@Vaarelsauce It refers to the number of parallel tasks, the render time will be faster with higher processes (but too high will be slower depending on your pc's spec, usually 2-4 processes are enough on a normal pc). By the way you can hover each setting for more informations.

I don't see how pre-existing resolutions is better than being able to enter the width and height separately.
