### ISSUE TITLE
AR lowered after rendering in 720FPS

### ISSUE THREAD

**Issue by takimikuu** [uyitroa/osr2mp4-app#51]
After I rendered a 6 minute map replay in 720FPS (because I tried to make the motion blur effect after in Vegas), it looks like AR got lowered and circles now look like they are getting hit early.

Video: https://www.youtube.com/watch?v=OFD7Ph37TrE&feature=youtu.be

**Comment by uyitroa** [comment]
yeah it's a known issue. But there is a temporary fix if you are interested.
https://www.youtube.com/watch?v=c1b20D7EHrg

The fix should be around 3:03

**Comment by uyitroa** [comment]
update the app if you still encounter this issue
