### ISSUE TITLE
Can't change font for PP counter

### ISSUE THREAD

**Issue by Daithi** [uyitroa/osr2mp4-app#54]
I'm trying to use Calibri Bold and I have the .ttf file in the same folder as the Arial ones that come with the program; however, when I change the name of the font file in the PP counter options it just defaults to the scoreentry images. I've tried renaming my new font but it doesn't seem to make a difference.

**Comment by uyitroa** [comment]
@Daithi  try putting the .ttf file to the same folder as osr2mp4.exe

**Comment by Daithi** [comment]
That worked, thank you! Now, is there a way to make it use the bold version of the font?

**Comment by uyitroa** [comment]
@Daithi I'm not very knowledgeable about fonts, but can't you just download the .ttf bold version of the font and put in the osr2mp4 folder to use it?

**Comment by Daithi** [comment]
@uyitroa well I have the bold version of the font but it seems like it’s packaged with the regular version, so both are in the .ttf file and it’s up to text editing programs to choose between different font weights. I’ll try to either find one that has only the bold version or edit the .ttf so that it only includes the bold lettering. I’ll let you know how it works out.
