### ISSUE TITLE
Hitting start immediately throws an error.

### ISSUE THREAD

**Issue by StrawberryMahjong** [uyitroa/osr2mp4-app#59]
`ImportError("cannot import name 'UnidentifiedImageError' from 'PIL' (C:\\Users\\User\\AppData\\Roaming\\Python\\Python37\\site-packages\\PIL\\__init__.py)")cannot import name 'UnidentifiedImageError' from 'PIL' (C:\Users\User\AppData\Roaming\Python\Python37\site-packages\PIL\__init__.py) Traceback (most recent call last):
  File "libs/pythonlib/lib/site-packages/osr2mp4app/run_osu.py", line 92, in <module>
    run()
  File "libs/pythonlib/lib/site-packages/osr2mp4app/run_osu.py", line 31, in run
    from osr2mp4.osr2mp4 import Osr2mp4
  File "C:\Users\User\Desktop\osr2mp4\libs\pythonlib\lib\site-packages\osr2mp4\osr2mp4.py", line 25, in <module>
    from osr2mp4.VideoProcess.CreateFrames import create_frame
  File "C:\Users\User\Desktop\osr2mp4\libs\pythonlib\lib\site-packages\osr2mp4\VideoProcess\CreateFrames.py", line 9, in <module>
    from osr2mp4.VideoProcess.Draw import draw_frame, Drawer
  File "C:\Users\User\Desktop\osr2mp4\libs\pythonlib\lib\site-packages\osr2mp4\VideoProcess\Draw.py", line 15, in <module>
    from osr2mp4.VideoProcess.AFrames import *
  File "C:\Users\User\Desktop\osr2mp4\libs\pythonlib\lib\site-packages\osr2mp4\VideoProcess\AFrames.py", line 4, in <module>
    from osr2mp4.ImageProcess.PrepareFrames.Scores.URArrow import prepare_urarrow
  File "C:\Users\User\Desktop\osr2mp4\libs\pythonlib\lib\site-packages\osr2mp4\ImageProcess\PrepareFrames\Scores\URArrow.py", line 3, in <module>
    from osr2mp4.ImageProcess.PrepareFrames.YImage import YImage
  File "C:\Users\User\Desktop\osr2mp4\libs\pythonlib\lib\site-packages\osr2mp4\ImageProcess\PrepareFrames\YImage.py", line 5, in <module>
    from PIL import Image, UnidentifiedImageError
ImportError: cannot import name 'UnidentifiedImageError' from 'PIL' (C:\Users\User\AppData\Roaming\Python\Python37\site-packages\PIL\__init__.py)
`
What can I do to prevent this?

**Comment by uyitroa** [comment]
open cmd, try
```
pip uninstall pil
pip install pillow```

**Comment by StrawberryMahjong** [comment]
`C:\Users\User>pip uninstall pil
Cannot uninstall requirement pil, not installed
You are using pip version 9.0.1, however version 20.3.3 is available.
You should consider upgrading via the 'python -m pip install --upgrade pip' command.

C:\Users\User>pip install pillow
Requirement already satisfied: pillow in c:\program files\python36\lib\site-packages
You are using pip version 9.0.1, however version 20.3.3 is available.
You should consider upgrading via the 'python -m pip install --upgrade pip' command.`

Didn't seem to work but I tried to export again, and it threw the same error.

**Comment by uyitroa** [comment]
try 
```
pip install pillow --upgrade
```

**Comment by StrawberryMahjong** [comment]
`C:\WINDOWS\system32>pip install pillow --upgrade
Collecting pillow
  Using cached https://files.pythonhosted.org/packages/ca/dd/be2cc39f0609a9569fb7f96a9e2500134b6cf889a3c24039cf6f1bd92722/Pillow-8.1.0-cp36-cp36m-win_amd64.whl
Installing collected packages: pillow
  Found existing installation: Pillow 7.1.2
    Uninstalling Pillow-7.1.2:
      Successfully uninstalled Pillow-7.1.2
Successfully installed pillow-8.1.0
You are using pip version 9.0.1, however version 20.3.3 is available.
You should consider upgrading via the 'python -m pip install --upgrade pip' command.`

Still throws the same error in the program...

**Comment by uyitroa** [comment]
you can try uninstalling pillow then
```
pip uninstall pillow
```

And if you need pillow for your work or something like that then you can download https://www.lfd.uci.edu/~gohlke/pythonlibs/#pillow-simd
then open cmd in downloads folder, then do
```
pip install downloaded-file-name.whl
```

**Comment by StrawberryMahjong** [comment]
`  Successfully uninstalled Pillow-8.1.0
You are using pip version 9.0.1, however version 20.3.3 is available.
You should consider upgrading via the 'python -m pip install --upgrade pip' command.`

Still throwing the same error, I ended up getting it all to work by going to `C:\Users\User\AppData\Roaming\Python\Python37\site-packages` and deleting the PIL folder. Thank you for your time and help!
