### ISSUE TITLE
Memory error

### ISSUE THREAD

**Issue by ohmaytt** [uyitroa/osr2mp4-app#6]
![image](https://user-images.githubusercontent.com/45356936/87240374-fc278700-c453-11ea-8986-f8b55a87d1cf.png)
Getting this issue

I'm on laptop with both integrated and discrete GPU
I also have changed resolution from Rendering option to 1080p
I also have 16gb of memory

**+Edit 1** 
I also used high res skin
and tried to render my Raise my sword play and it showed the memory error

when I rendered tv size map with default skin it worked 

**+Edit 2**
Successfully rendered Raise My Sword replay with simple, clean skin

Failed to render a TV size map with high quality skin

The app's RAM usage rises up to 5gb then shows memory error when using high quality skin
[This is the skin causing error](https://www.reddit.com/r/OsuSkins/comments/h14wcr/%E3%83%9F%E3%83%8B%E3%83%9E%E3%83%AA%E3%82%B9%E3%83%88_minimalist_std_only_169_hdsd_animated/)

**Comment by uyitroa** [comment]
Please reproduce the error and send logs folder. Also can you send me the skin?

**Comment by ohmaytt** [comment]
[Logs memory error.zip](https://github.com/uyitroa/osr2mp4-app/files/4910144/Logs.memory.error.zip)

There you go
