### ISSUE TITLE
osr2mp4 Doesn't work in Linux as new PyQt5 doesn't have the needed imports

### ISSUE THREAD

**Issue by EllySensei** [uyitroa/osr2mp4-app#69]
I tried installing osr2mp4-app in Arch today, but it doesn't run, I have followed the build on Linux, but looking at it further, PyQt5 breaks the ProgressBar.py as it finds QWinTaskbarButton that doesn't exist on the Linux repos, this is the traceback
`Traceback (most recent call last):
  File "main.py", line 31, in <module>
    from HomeComponents.ProgressBar import ProgressBar
  File "/home/mafuyu/Programs/osr2mp4-app/HomeComponents/ProgressBar.py", line 6, in <module>
    from PyQt5.QtWinExtras import QWinTaskbarButton 
ModuleNotFoundError: No module named 'PyQt5.QtWinExtras'`

Theoretically there is a workaround that you can just get an existing Windows installation, get the PyQt5 files from there, put it in Linux, then try running it again, but I have not tried it, I haven't tried it running in Wine either, what could be your suggestion in making this work.

**Comment by stllok** [comment]
got the same error

**Comment by uyitroa** [comment]
Revert the change of these files of this pull request.

https://github.com/uyitroa/osr2mp4-app/pull/67

**Comment by stllok** [comment]
oof it works, thx owo

**Comment by FireRedz** [comment]
oh no
