### ISSUE TITLE
When I press start , it doesn't work

### ISSUE THREAD

**Issue by adrplays** [uyitroa/osr2mp4-app#79]
so i choose my map , made my settings from this video , https://www.youtube.com/watch?v=c1b20D7EHrg , did all good , even made a replay before , https://www.youtube.com/watch?v=U22v4cT_ah0&t=36s , and i tried to make another one , but it doesnt work anymore to me

images: https://imgur.com/a/slWYDCu

i really need help pls

**Comment by uyitroa** [comment]
The first error is probably die to your skin.

The second one is due to the folder that contains osr2mp4 folder doesn't have permission to do stuff. Try to move osr2mp4 somewhere else like Documents, Downloads, Music or even Program Files.
