### ISSUE TITLE
macOS installing dependencies failed

### ISSUE THREAD

**Issue by nerelly** [uyitroa/osr2mp4-app#89]
After entering "pip install -r requirements.txt" into terminal, it gives me a wall of red text with warnings. At the end of the wall of text, it says this:

> ERROR: Command errored out with exit status 1: /Users/username/.pyenv/versions/3.7.8/bin/python3.7 -u -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/var/folders/5y/n_rfgdvj2716_7qnykcs9rl00000gp/T/pip-install-4nsop7u0/pillow-simd_3159c4ada36447ae8dd4703a55c95a0c/setup.py'"'"'; __file__='"'"'/private/var/folders/5y/n_rfgdvj2716_7qnykcs9rl00000gp/T/pip-install-4nsop7u0/pillow-simd_3159c4ada36447ae8dd4703a55c95a0c/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /private/var/folders/5y/n_rfgdvj2716_7qnykcs9rl00000gp/T/pip-record-64mm9qs9/install-record.txt --single-version-externally-managed --compile --install-headers /Users/username/.pyenv/versions/3.7.8/include/python3.7m/Pillow-SIMD Check the logs for full command output.

Another thing to note is that when I ran "pip uninstall PIL Pillow", it gave me this output:

> WARNING: Skipping PIL as it is not installed.
WARNING: Skipping Pillow as it is not installed.

Any solutions?

**Comment by uyitroa** [comment]
Replace Pillow-SIMD with Pillow in requirements.txt and run it again.

Don't do 'pip uninstall Pillow' after that.

**Comment by nerelly** [comment]
> Replace Pillow-SIMD with Pillow in requirements.txt and run it again.
> 
> Don't do 'pip uninstall Pil Pillow' after that.

Thanks! Fixed the problem.
