### ISSUE TITLE
Can't open osr2map (mac)

### ISSUE THREAD

**Issue by SWAGEDGAR** [uyitroa/osr2mp4-app#90]
When putting `python main.py` it responds with
`  File "main.py", line 6, in <module>
    import PyQt5
ImportError: No module named PyQt5`

**Comment by uyitroa** [comment]
do 'pip install -r requirements.txt'

**Comment by SWAGEDGAR** [comment]
Responds with:
`[Big-Brain-iMac:~ SwagEdgar$ python main.py`
`/usr/local/bin/python: can't open file '/Users/ree/main.py': [Errno 2] No such file or directory`

**Comment by SWAGEDGAR** [comment]
`Big-Brain-iMac:~ SwagEdgar$ pip install --upgrade pip`
`Requirement already satisfied: pip in /usr/local/lib/python3.9/site-packages (21.1.2)`

**Comment by uyitroa** [comment]
what?
I said to do `pip install -r requirements.txt` not `pip install --upgrade pip`

**Comment by SWAGEDGAR** [comment]
> what?
> I said to do `pip install -r requirements.txt` not `pip install --upgrade pip`

he my bad lol 
`Big-Brain-iMac:~ SwagEdgar$ pip install -r requirements.txt`
`ERROR: Could not open requirements file: [Errno 2] No such file or directory: 'requirements.txt'`

**Comment by Hoshiiiii** [comment]
> > what?
> > I said to do `pip install -r requirements.txt` not `pip install --upgrade pip`
> 
> my bad lol
> `Big-Brain-iMac:~ SwagEdgar$ pip install -r requirements.txt`
> `ERROR: Could not open requirements file: [Errno 2] No such file or directory: 'requirements.txt'`

are you sure that your command line is already in the osr2mp4 directory when you do pip install -r requirements.txt? cause if not then do it

**Comment by SWAGEDGAR** [comment]
> > > what?
> > > I said to do `pip install -r requirements.txt` not `pip install --upgrade pip`
> > 
> > 
> > my bad lol
> > `Big-Brain-iMac:~ SwagEdgar$ pip install -r requirements.txt`
> > `ERROR: Could not open requirements file: [Errno 2] No such file or directory: 'requirements.txt'`
> 
> are you sure that your command line is already in the osr2mp4 directory when you do pip install -r requirements.txt? cause if not then do it

thanks I forgot to change it. thank both of you guys its up and working.
